force-app/main/default/objects/Product2/fields/Review_Average__c.field-meta.xml
<CustomField>
    <fullName>Review_Average__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Review Average</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Review_Count__c.field-meta.xml
<CustomField>
    <fullName>Review_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Review Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReviewTriggerHandler.cls
public with sharing class ReviewTriggerHandler implements ITriggerHandler {
        public static Boolean TriggerDisabled = false;
        public Boolean IsDisabled() {
            return TriggerDisabled;
        }
        public void BeforeInsert(List<SObject> newItems) {
        }
        public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        }
        public void BeforeDelete(Map<Id, SObject> oldItems) {
        }
        public void AfterInsert(Map<Id, SObject> newItems) {
            Decimal amount;
            Decimal average;
            List <Review__c> newReviews = newItems.values();
            String productId = newReviews.get(0).ProductId__c;
            Product2 product = [SELECT Id, Name, Review_Average__c, Review_Count__c FROM Product2 WHERE Id=:productId];
            amount = product.Review_Count__c;
            average = product.Review_Average__c * amount;
            for (Review__c review : newReviews){
                average += review.Rating__c;
                amount++;
            }
            product.Review_Count__c = amount;
            product.Review_Average__c = (average/amount).setScale(1);
            try {
                update product;
            } catch (Exception e) {
                System.debug(e.getMessage());
            }
        }
        public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        }
        public void AfterDelete(Map<Id, SObject> oldItems) {
            Decimal amount;
            Decimal average;
            List <Review__c> oldReviews = oldItems.values();
            String productId = oldReviews.get(0).ProductId__c;
            Product2 product = [SELECT Id, Name, Review_Average__c, Review_Count__c FROM Product2 WHERE Id=:productId];
            amount = product.Review_Count__c;
            average = product.Review_Average__c * amount;
            for (Review__c review : oldReviews){
                average -= review.Rating__c;
                amount--;
            }
            product.Review_Count__c = amount;
            product.Review_Average__c = (average/amount).setScale(1);
            try {
                update product;
            } catch (Exception e) {
                System.debug(e.getMessage());
            }
        }
        public void AfterUndelete(Map<Id, SObject> oldItems) {
        }
}