force-app/main/default/objects/Product2/fields/Review_Count__c.field-meta.xml
<CustomField>
    <fullName>Review_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Review Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReviewTriggerHandlerTest.cls
@isTest
private class ReviewTriggerHandlerTest{
    @isTest static void TestAfterUpdateWithOneReview() {
        Product2 product = new Product2(Name='Test Product');
        insert product;
        Review__c review = new Review__c();
        review.Status__c = 'New';
        review.ProductId__c = product.Id;
        review.Rating__c = 5;
        insert review;
        review.Status__c = 'Approved';

        Test.startTest();
        Database.SaveResult result = Database.update(review, false);
        Product2 productResult = [
                SELECT Id, Name, Review_Count__c FROM Product2
                WHERE Id= :product.Id];
        Test.stopTest();

        System.assert(result.isSuccess());
        System.assertEquals(1, productResult.Review_Count__c);
    }
}